### ISSUE TITLE
please update the ttf2woff version 

### ISSUE THREAD

**Issue by webxmsj** [hzsrc/webpack-iconfont-plugin-nodejs#12]
webpack-iconfont-plugin-nodejs  v1.0.19
node v14.15.5
请更新下包版本，现在有错误警告, 
/node_modules/ttf2woff2-no-gyp/jssrc/ttf2woff2.js:3 Invalid asm.js: Invalid member of stdlib

**Comment by hzsrc** [comment]
已更新解决，谢谢
