### ISSUE TITLE
怎么用的呢？

### ISSUE THREAD

**Issue by luchanan** [hzsrc/webpack-iconfont-plugin-nodejs#17]
删掉了svg文件下的东西，用上自己的，npm run dev还是原来那些，没有效果的

**Comment by hzsrc** [comment]
git clone https://github.com/hzsrc/webpack-iconfont-plugin-nodejs.git
然后npm i && npm run dev，即可查看效果。
这个项目有使用它：https://github.com/hzsrc/vue-element-ui-scaffold-webpack4
