### ISSUE TITLE
Watch issue

### ISSUE THREAD

**Issue by hakaba** [hzsrc/webpack-iconfont-plugin-nodejs#18]
If you are not in watch mode compile anyway.

As there is probably a better way to detect watch mode, I do not make de pull request.

in src/index.js, change the apply function like this :

`    apply(compiler) {
        // 生成的字体和css会被作为源码被提交，故npm run build时不需再次生成。
        // 而生成的字体和css在npm run dev时也会被webpack监听（watch），所以只需在svg变动时，重新生成字体和css即可
      this.compile()
        if (process.env.NODE_ENV === 'development' || process.env.NODE_ENV === undefined) {
            //this.getBinder(compiler, 'run')(this.compile);
            this.watch();
        }
    }
`

**Comment by hzsrc** [comment]
This maybe cause a duplicated compiling

**Comment by hakaba** [comment]
@hzsrc I miss the point.
In my usage, if I set `process.env.NODE_ENV = 'prod'` there is no build neither watch.
If I set `process.env.NODE_ENV = 'development'` I have build BUT watch.

How can I build fonts, css and html without watching (as there is more step in my CI) ?

Thanks
