### ISSUE TITLE
When you start the plugin, after processing the console continues to hang as if waiting for something, is it possible to start the process without watcher?

### ISSUE THREAD

**Issue by saschati** [hzsrc/webpack-iconfont-plugin-nodejs#32]
There are no errors, well, I think it's not a mistake, but a planned logic, but is it possible to disable it, such as that some other processes can be performed after the build. 
 It seems to me that this code affects this https://i.imgur.com/ikzFSQ3.png  , but if you do not comment on the above and comment on the lower code, everything works fine, is it possible to add a switch here through options or the like?

**Comment by hzsrc** [comment]
Hi, 1.0.26 add a `notWatchFile` option.
Thanks!
