### ISSUE TITLE
 the icon generated not like the general svg

### ISSUE THREAD

**Issue by Tanglongwen** [hzsrc/webpack-iconfont-plugin-nodejs#38]
I have a svg like this
![close](https://user-images.githubusercontent.com/21996836/190336394-47217fe9-5fe2-473f-8b3f-b69689df4e52.svg)

but when I use by nodejs，finallly it generates the icon not like the general svg
![image](https://user-images.githubusercontent.com/21996836/190336538-77425f6a-dc7b-49ff-b78d-cfd375912ffd.png)

**Comment by hzsrc** [comment]
It may be like this: the svg has white backgroud color.
Dont use backgroud color can fix this

**Comment by hzsrc** [comment]
This is your svg file, you can open it by chrome and see it:
https://user-images.githubusercontent.com/21996836/190336394-47217fe9-5fe2-473f-8b3f-b69689df4e52.svg
