### ISSUE TITLE
我的svg转换之后都变成了方块。。

### ISSUE THREAD

**Issue by sdz123** [hzsrc/webpack-iconfont-plugin-nodejs#4]

**Comment by sdz123** [comment]
直接用的preview-html页面，热更新之后所有字体也都变成了方块。。

**Comment by hzsrc** [comment]
怎么重现？

**Comment by sdz123** [comment]
正常打开项目的文件夹，找到svg那个文件，然后直接复制进来一批svg图片（19个），然后页面自动刷新，都变成了小方块，
![image](https://user-images.githubusercontent.com/19849443/61676186-98c9b400-ad2d-11e9-8f1a-c7ea3899fc05.png)

**Comment by sdz123** [comment]
![image](https://user-images.githubusercontent.com/19849443/61691832-fc200a00-ad5e-11e9-8231-b27e62e0d37f.png)
这里是不是要设置一下默认的cssTemplate？

**Comment by hzsrc** [comment]
svg是否标准？文件名有中文吗？

**Comment by sdz123** [comment]
遇到了另一个问题。
![image](https://user-images.githubusercontent.com/19849443/61706622-1ec01c00-ad7b-11e9-86af-0d71771ee701.png)
运行到这里，每次都会报illegal operation on a directory,

**Comment by hzsrc** [comment]
有问题的svg能否发上来看下？

**Comment by sdz123** [comment]
[蒙版组 72.svg.zip](https://github.com/hzsrc/webpack-iconfont-plugin-nodejs/files/3424908/72.svg.zip)

**Comment by sdz123** [comment]
方块的问题解决了，还是报illegal operation on a directory的问题没解决，应该是我们项目的问题，我决定单独起一个文件来跑这个插件然后把fonts文件导到我们的项目。谢谢您的耐心回复！

**Comment by hzsrc** [comment]
你可以试下不走webpack，直接用node允许的模式：npm run build-font。
