### ISSUE TITLE
Retain Unicode Value 

### ISSUE THREAD

**Issue by johnthachil** [hzsrc/webpack-iconfont-plugin-nodejs#7]
Hey is there a way to retain the unicode glyph every-time we generate fonts. Any new icon added should only append to current of unicodes ?

**Comment by hzsrc** [comment]
Just use a `startUnicode` option:

````js
{
    fontName: 'my-app-icon',
    // template: path.join(dir, 'src/fonts/css.njk'),
    svgs: path.join(dir, 'src/svgs/*.svg'),
    fontsOutput: path.join(dir, 'src/fonts/'),
    cssOutput: path.join(dir, 'src/fonts/font.css'),
    jsOutput: path.join(dir, 'src/fonts/fonts.js'),
    htmlOutput: path.join(dir, 'src/fonts/font-preview.html'),
    //formats: ['ttf', 'woff2', 'woff', 'svg'],
    cssPrefix: 'my-icon',
    startUnicode: 33,
};
````

**Comment by johnthachil** [comment]
I still didn't understand how can we retain previous set of unicodes by using "startUnicode" option. I want to build design system Icon library where I add each svg it append existing list of font system?

With default option icons are ordered alphabetically.

**Comment by hzsrc** [comment]
Perhaps your need to set a customized `metadataProvider`, to set unicode by yourself:
https://www.npmjs.com/package/svgicons2svgfont




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Thachil"<notifications@github.com&gt;; 
发送时间: 2020年1月6日(星期一) 下午5:52
收件人: "hzsrc/webpack-iconfont-plugin-nodejs"<webpack-iconfont-plugin-nodejs@noreply.github.com&gt;; 
抄送: "5953107"<hz932@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [hzsrc/webpack-iconfont-plugin-nodejs] Retain Unicode Value  (#7)




I still didn't understand how can we retain previous set of unicodes by using "startUnicode" option. I want to build design system Icon library where I add each svg it append existing list of font system?
 
With default option icons are ordered alphabetically.
