### ISSUE TITLE
Pusblishing a new version of webpack-iconfont-plugin-nodejs on NPM

### ISSUE THREAD

**Issue by madarche** [hzsrc/webpack-iconfont-plugin-nodejs#8]
Nǐ hǎo @hzsrc 

The published version of your NPM package is affected by this vulnerability: https://www.npmjs.com/advisories/1650

Would it be possible for you to publish a new version of this package in the NPM registry please?

🙇‍‍♂️ Tsaï Tien

**Comment by hzsrc** [comment]
I have noticed that, and when I tried to fix it, I found that the `xmldom` is depended indirectly. I didn't find a way to resolve it yet.

**Comment by madarche** [comment]
@hzsrc 谢谢

You just have to delete the `package-lock.json` file and the `node_modules` directory, and then doing a fresh `npm install`. This will make `npm` create a new up-to-date `package-lock.json` that will make a successful `npm audit` with a return result of:

`found 0 vulnerabilities`

The commands to execute (if on an Unix-like system like Linux) :
```shell
rm package-lock.json && rm -rf node_modules && npm install
npm audit
```

The reason why: The *svg2ttf* package has been fixed some days ago https://github.com/fontello/svg2ttf/commit/60679f02264830d846ce0be5024e56bf35679f7d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 and by specifying `"svg2ttf": "^5.1.0"` in *webpack-iconfont-plugin-nodejs* `package.json` file the other applications depending on *webpack-iconfont-plugin-nodejs* will receive the newest version of *svg2ttf* with the following constraint: 5.1.0 <= svg2ttf < 6.0.0

So to fix the content of this Git repository you just have to regenerate a new `package-lock.json` file 🎉

And to fix the published package on NPM would even be simpler, since you would just have to publish the actual content of this Git repository right now because the  `package-lock.json` file is not (and should not) published on NPM! 🎉 But of course it's cleaner and more logical to fix the content of the Git repository first, and then to publish on NPM.

再联系

**Comment by hzsrc** [comment]
@madarche  Thanks  a lot! I will try it.

**Comment by hzsrc** [comment]
webpack-iconfont-plugin-nodejs@1.0.18 published. Thanks!

**Comment by madarche** [comment]
@hzsrc Thanks a lot! Thanks for this fix and the publication on NPM 🙇‍‍♂️
