### ISSUE TITLE
Putting git tags by using "npm version patch",  "npm version minor", etc.

### ISSUE THREAD

**Issue by madarche** [hzsrc/webpack-iconfont-plugin-nodejs#9]
Hello again @hzsrc 

I would like to be able to follow and potentially contribute to *webpack-iconfont-plugin-nodejs* more easily. And git *tags* would be very helpful to do that.

It is a good practice to put in the git repository the *tags* corresponding to the released packages.

There is a very easy way to do that by using the `npm version` CLI:
* https://docs.npmjs.com/cli/v7/commands/npm-version
* https://docs.npmjs.com/cli/v6/commands/npm-version

For example, at the moment, to create an **webpack-iconfont-plugin-nodejs@1.0.20** version and create the corresponding git tag automatically, you would just have to execute:
```shell
npm version patch
```

For example, at the moment, to create an **webpack-iconfont-plugin-nodejs@1.1.0** version and create the corresponding git tag automatically, you would just have to execute:
```shell
npm version minor
```

For example, at the moment, to create an **webpack-iconfont-plugin-nodejs@2.0.0** version and create the corresponding git tag automatically, you would just have to execute:
```shell
npm version major
```

And then finally be sure to push the git tags to the repository on GitHub! With the git CLI this is done with the following command:
```shell
git push --follow-tags
```

谢谢

**Comment by hzsrc** [comment]
Thank you very much!  This makes  more easily to publish a version. I will try it next time.

**Comment by madarche** [comment]
@hzsrc you're welcome! I'm happy to help on free/libre software that benefit everyone!
